const CHUNK_SIZE_BYTES = 1024 * 512;
const AES_PADDING_BYTES = 16;
const INITIALIZATION_VECTOR_BYTES = 12;

const APPLICATION_CHUNK_SIZE =
  CHUNK_SIZE_BYTES + AES_PADDING_BYTES + INITIALIZATION_VECTOR_BYTES;

module.exports = {
  CHUNK_SIZE_BYTES,
  AES_PADDING_BYTES,
  INITIALIZATION_VECTOR_BYTES,
  APPLICATION_CHUNK_SIZE,
  CHUNK_SIZE_BYTES,
};
